### ISSUE TITLE
To protect our users, we can't process your request right now.

### ISSUE THREAD

**Issue by hzxie** [cuber/ngx_http_google_filter_module#126]
When I tried to access Google Scholar, I got following message:

![screenshot from 2017-01-01 13 43 02](https://cloud.githubusercontent.com/assets/1730504/21580325/431ad730-d028-11e6-9c8c-80a334803e2d.png)

But it works a few days ago. Maybe it's time for you to update your module :)

**Comment by cuber** [comment]
This is because google has banned your ip, google scholar has banned some VPS provider like digital ocean, vultr, linode.
This is an workaround if your VPS support ipv6, force the scholar to use ipv6 by /etc/hosts.
Please see this project for more detail about google ipv6 https://github.com/lennylxx/ipv6-hosts
